//
// ROOT macro: Bfield.C (autogenerated by xyscan)
// xyscan Version 4.3.0
// Date: Tue Sep 28 11:19:35 2021
// Scanned by: axeld
// Source: Clipboard
// Comment: 
//
#include "TROOT.h"
#include "TH1D.h"
#include "TCanvas.h"
#include "TStyle.h"
#include "TGraphAsymmErrors.h"

void Bfield()
{
    gROOT->SetStyle("Plain");
    gStyle->SetOptFit(0);
    gStyle->SetOptStat(0);

    TCanvas *c1 = new TCanvas("c1","xyscan Data Display",720,540);
    c1->SetTickx(1);
    c1->SetTicky(1);
    c1->SetBorderSize(1);
    c1->SetFillColor(0);

    TH1D *histo = new TH1D("histo","xyscan", 100, -0.329617, 3.29617);
    histo->SetMinimum(-0.996982);
    histo->SetMaximum(0.0898182);
    histo->SetStats(false);
    histo->GetXaxis()->SetTitle("x");
    histo->GetYaxis()->SetTitle("y");
    gPad->SetLogy(0);
    gPad->SetLogx(0);
    histo->Draw();

    double x[31];
    double y[31];
    double dxlow[31];
    double dxup[31];
    double dylow[31];
    double dyup[31];
    int n = 0;
    x[n] = 0.0;	        y[n] = -0.898182;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 0.10;	y[n] = -0.894545;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 0.20;	y[n] = -0.876364;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 0.30;	y[n] = -0.847273;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 0.40;	y[n] = -0.803636;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 0.50;	y[n] = -0.750909;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 0.60;	y[n] = -0.689091;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 0.698725;	y[n] = -0.623636;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 0.799537;	y[n] = -0.563636;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 0.900348;	y[n] = -0.510909;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 1.00116;	y[n] = -0.461818;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 1.10197;	y[n] = -0.42;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 1.1993;	y[n] = -0.385455;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 1.30012;	y[n] = -0.349091;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 1.40093;	y[n] = -0.314545;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 1.50174;	y[n] = -0.278182;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 1.59907;	y[n] = -0.245455;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 1.69988;	y[n] = -0.210909;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 1.8007;	y[n] = -0.178182;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 1.90151;	y[n] = -0.147273;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 1.99884;	y[n] = -0.118182;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 2.09965;	y[n] = -0.0945455;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 2.19699;	y[n] = -0.0745455;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 2.2978;	y[n] = -0.0581818;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 2.39861;	y[n] = -0.0436364;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 2.49942;	y[n] = -0.0327273;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 2.60023;	y[n] = -0.0236364;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 2.69757;	y[n] = -0.0181818;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 2.80185;	y[n] = -0.0127273;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 2.89919;	y[n] = -0.00909091;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 2.99652;	y[n] = -0.00545455;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;

    TGraphAsymmErrors *xyscan = new TGraphAsymmErrors(n, x, y, dxlow, dxup, dylow, dyup);
    xyscan->SetMarkerStyle(20);
    xyscan->SetMarkerColor(1);
    xyscan->Draw("PE same");

    int nDC=23;
    int nTot=n;
    float dr = 0.1;
    float sumB = 0;
    float sumDC = 0;
    double sumB_conv[31];
    double mass_conv[31];

    for (int i=1; i<n;i++){
        sumB = sumB + (y[i]+y[i-1])/2*dr;
        if (i<nDC){
            sumDC = sumDC + (y[i]+y[i-1])/2*dr;
        } else if(i == nDC) {
            sumDC = sumDC + dr*(y[i-1] + (y[i]-y[i-1])/4.);
        }
    }
    cout << endl;
    cout << " full field integral: " << 0.3*sumB << " rad GeV  ---  DC field integral: " << 0.3*sumDC << " rad GeV  --- ratio ="  << sumB/sumDC << endl;

    sumB = 0; 
    int i = 0;
    sumB_conv[i] = sumB;
    mass_conv[i] = 0;
    cout << " effective field bent at " << 10*i << " cm  "  <<  sumB_conv[i] << " mrad GeV " << endl; 
    for (i=1; i<n; i++){
         sumB = sumB + 0.3* (y[i]+y[i-1])/2*dr;
         sumB_conv[i] = sumB;
         mass_conv[i] = -250*sumB_conv[i]*4/.25;
    cout << " effective field bent at " << 10*i << " cm  "  <<  sumB_conv[i] << " mrad GeV " << endl; 
    }

    TGraphAsymmErrors *openangle = new TGraphAsymmErrors(n, x, sumB_conv, dxlow, dxup, dylow, dyup);
    openangle->SetMarkerStyle(20);
    openangle->SetMarkerColor(1);
    openangle->Draw("PE same");

    TCanvas *c2 = new TCanvas("c2","xyscan Data Display",720,540);
    c1->SetTickx(1);
    c1->SetTicky(1);
    c1->SetBorderSize(1);
    c1->SetFillColor(0);

    TH1D *histo1 = new TH1D("histo1","", 100, 0, .99);
    histo1->SetMinimum(0.);
    histo1->SetMaximum(1000);
    histo1->SetStats(false);
    histo1->GetXaxis()->SetTitle("r [cm]");
    histo1->GetYaxis()->SetTitle("mass [MeV]");
    gPad->SetLogy(0);
    gPad->SetLogx(0);
    histo1->Draw();

    TGraphAsymmErrors *mass = new TGraphAsymmErrors(n, x, mass_conv, dxlow, dxup, dylow, dyup);
    mass->SetMarkerStyle(20);
    mass->SetMarkerColor(1);
    mass->Draw("PE same");



}
